-- GolfStats database tables
-- Execute this SQL in the Supabase SQL Editor to create all tables

-- User preferences table
CREATE TABLE IF NOT EXISTS public.user_preferences (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) not null,
    preferred_units varchar(10) default 'yards',
    handicap varchar(10),
    home_course varchar(255),
    phone varchar(50),
    avatar_url varchar(255),
    trackman_username varchar(255),
    trackman_password varchar(255),
    arccos_email varchar(255),
    arccos_password varchar(255),
    skytrak_username varchar(255),
    skytrak_password varchar(255),
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    UNIQUE(user_id)
);
-- Add RLS policies
ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own preferences" 
    ON public.user_preferences FOR SELECT 
    USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own preferences" 
    ON public.user_preferences FOR INSERT 
    WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own preferences" 
    ON public.user_preferences FOR UPDATE 
    USING (auth.uid() = user_id);

-- Golf rounds table
CREATE TABLE IF NOT EXISTS public.golf_rounds (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) not null,
    date timestamp with time zone not null,
    course_name varchar(255) not null,
    course_location varchar(255),
    tee_color varchar(50),
    total_score integer,
    total_par integer,
    front_nine_score integer,
    back_nine_score integer,
    weather_conditions varchar(100),
    notes text,
    source_system varchar(50),
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);
-- Add RLS policies
ALTER TABLE public.golf_rounds ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own rounds" 
    ON public.golf_rounds FOR SELECT 
    USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own rounds" 
    ON public.golf_rounds FOR INSERT 
    WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own rounds" 
    ON public.golf_rounds FOR UPDATE 
    USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own rounds" 
    ON public.golf_rounds FOR DELETE 
    USING (auth.uid() = user_id);

-- Golf holes table
CREATE TABLE IF NOT EXISTS public.golf_holes (
    id bigint generated by default as identity primary key,
    round_id bigint references public.golf_rounds(id) on delete cascade not null,
    hole_number integer not null,
    par integer not null,
    score integer,
    fairway_hit boolean,
    green_in_regulation boolean,
    putts integer,
    distance_yards integer,
    notes text,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);
-- Add RLS policies 
ALTER TABLE public.golf_holes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own holes through rounds" 
    ON public.golf_holes FOR SELECT 
    USING (EXISTS (
        SELECT 1 FROM public.golf_rounds
        WHERE public.golf_rounds.id = round_id 
        AND public.golf_rounds.user_id = auth.uid()
    ));
CREATE POLICY "Users can insert holes to their own rounds" 
    ON public.golf_holes FOR INSERT 
    WITH CHECK (EXISTS (
        SELECT 1 FROM public.golf_rounds
        WHERE public.golf_rounds.id = round_id 
        AND public.golf_rounds.user_id = auth.uid()
    ));
CREATE POLICY "Users can update holes of their own rounds" 
    ON public.golf_holes FOR UPDATE 
    USING (EXISTS (
        SELECT 1 FROM public.golf_rounds
        WHERE public.golf_rounds.id = round_id 
        AND public.golf_rounds.user_id = auth.uid()
    ));
CREATE POLICY "Users can delete holes of their own rounds" 
    ON public.golf_holes FOR DELETE 
    USING (EXISTS (
        SELECT 1 FROM public.golf_rounds
        WHERE public.golf_rounds.id = round_id 
        AND public.golf_rounds.user_id = auth.uid()
    ));

-- Golf shots table
CREATE TABLE IF NOT EXISTS public.golf_shots (
    id bigint generated by default as identity primary key,
    hole_id bigint references public.golf_holes(id) on delete cascade not null,
    shot_number integer not null,
    club varchar(50),
    distance_yards real,
    from_location varchar(50),
    to_location varchar(50),
    is_penalty boolean default false,
    ball_speed_mph real,
    club_speed_mph real,
    smash_factor real,
    launch_angle_degrees real,
    spin_rate_rpm real,
    spin_axis_degrees real,
    carry_distance_yards real,
    total_distance_yards real,
    side_deviation_yards real,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);
-- Add RLS policies (complex - linking through multiple tables)
ALTER TABLE public.golf_shots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own shots through holes and rounds" 
    ON public.golf_shots FOR SELECT 
    USING (EXISTS (
        SELECT 1 FROM public.golf_holes
        JOIN public.golf_rounds ON public.golf_rounds.id = public.golf_holes.round_id
        WHERE public.golf_holes.id = hole_id 
        AND public.golf_rounds.user_id = auth.uid()
    ));
CREATE POLICY "Users can insert shots to their own holes" 
    ON public.golf_shots FOR INSERT 
    WITH CHECK (EXISTS (
        SELECT 1 FROM public.golf_holes
        JOIN public.golf_rounds ON public.golf_rounds.id = public.golf_holes.round_id
        WHERE public.golf_holes.id = hole_id 
        AND public.golf_rounds.user_id = auth.uid()
    ));
CREATE POLICY "Users can update shots in their own holes" 
    ON public.golf_shots FOR UPDATE 
    USING (EXISTS (
        SELECT 1 FROM public.golf_holes
        JOIN public.golf_rounds ON public.golf_rounds.id = public.golf_holes.round_id
        WHERE public.golf_holes.id = hole_id 
        AND public.golf_rounds.user_id = auth.uid()
    ));
CREATE POLICY "Users can delete shots in their own holes" 
    ON public.golf_shots FOR DELETE 
    USING (EXISTS (
        SELECT 1 FROM public.golf_holes
        JOIN public.golf_rounds ON public.golf_rounds.id = public.golf_holes.round_id
        WHERE public.golf_holes.id = hole_id 
        AND public.golf_rounds.user_id = auth.uid()
    ));

-- Round stats table
CREATE TABLE IF NOT EXISTS public.round_stats (
    id bigint generated by default as identity primary key,
    round_id bigint references public.golf_rounds(id) on delete cascade not null unique,
    score_to_par integer,
    fairways_hit integer,
    fairways_total integer,
    greens_in_regulation integer,
    putts_total integer,
    putts_per_hole real,
    sand_saves integer,
    sand_save_attempts integer,
    penalties integer,
    average_drive_yards real,
    scrambling_successful integer,
    scrambling_attempts integer,
    up_and_downs integer,
    up_and_down_attempts integer,
    three_putts integer,
    extended_stats jsonb,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);
-- Add RLS policies
ALTER TABLE public.round_stats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own round stats" 
    ON public.round_stats FOR SELECT 
    USING (EXISTS (
        SELECT 1 FROM public.golf_rounds
        WHERE public.golf_rounds.id = round_id 
        AND public.golf_rounds.user_id = auth.uid()
    ));
CREATE POLICY "Users can insert stats for their own rounds" 
    ON public.round_stats FOR INSERT 
    WITH CHECK (EXISTS (
        SELECT 1 FROM public.golf_rounds
        WHERE public.golf_rounds.id = round_id 
        AND public.golf_rounds.user_id = auth.uid()
    ));
CREATE POLICY "Users can update stats for their own rounds" 
    ON public.round_stats FOR UPDATE 
    USING (EXISTS (
        SELECT 1 FROM public.golf_rounds
        WHERE public.golf_rounds.id = round_id 
        AND public.golf_rounds.user_id = auth.uid()
    ));
CREATE POLICY "Users can delete stats for their own rounds" 
    ON public.round_stats FOR DELETE 
    USING (EXISTS (
        SELECT 1 FROM public.golf_rounds
        WHERE public.golf_rounds.id = round_id 
        AND public.golf_rounds.user_id = auth.uid()
    ));

-- Clubs table
CREATE TABLE IF NOT EXISTS public.clubs (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) not null,
    name varchar(100) not null,
    club_type varchar(50) not null,
    brand varchar(100),
    model varchar(100),
    loft real,
    avg_distance_yards real,
    max_distance_yards real,
    is_active boolean default true,
    notes text,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);
-- Add RLS policies
ALTER TABLE public.clubs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own clubs" 
    ON public.clubs FOR SELECT 
    USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own clubs" 
    ON public.clubs FOR INSERT 
    WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own clubs" 
    ON public.clubs FOR UPDATE 
    USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own clubs" 
    ON public.clubs FOR DELETE 
    USING (auth.uid() = user_id);

-- Function to get a user ID by their email address
CREATE OR REPLACE FUNCTION public.get_user_id_by_email(email_address text)
RETURNS uuid
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT id 
  FROM auth.users 
  WHERE email = email_address
$$;