-- Range session tables for GolfStats
-- Execute this SQL in the Supabase SQL Editor to create range shot tables

-- Range sessions table
CREATE TABLE IF NOT EXISTS public.range_sessions (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) not null,
    date timestamp with time zone not null,
    location varchar(255) not null,
    duration_minutes integer,
    weather_conditions varchar(100),
    notes text,
    source_system varchar(50),
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);
-- Add RLS policies
ALTER TABLE public.range_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own range sessions" 
    ON public.range_sessions FOR SELECT 
    USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own range sessions" 
    ON public.range_sessions FOR INSERT 
    WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own range sessions" 
    ON public.range_sessions FOR UPDATE 
    USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own range sessions" 
    ON public.range_sessions FOR DELETE 
    USING (auth.uid() = user_id);

-- Range shots table
CREATE TABLE IF NOT EXISTS public.range_shots (
    id bigint generated by default as identity primary key,
    session_id bigint references public.range_sessions(id) on delete cascade not null,
    shot_number integer not null,
    club varchar(50),
    ball_speed_mph real,
    club_speed_mph real,
    smash_factor real,
    launch_angle_degrees real,
    spin_rate_rpm real,
    spin_axis_degrees real,
    carry_distance_yards real,
    total_distance_yards real,
    side_deviation_yards real,
    height_feet real,
    launch_direction_degrees real,
    from_pin_yards real,
    carry_side_feet real,
    carry_efficiency real, -- calculated as carry_distance_yards / ball_speed_mph
    height_to_carry_ratio real, -- calculated as height_feet / carry_distance_yards
    spin_to_launch_ratio real, -- calculated as spin_rate_rpm / launch_angle_degrees
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);
-- Add RLS policies
ALTER TABLE public.range_shots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own range shots" 
    ON public.range_shots FOR SELECT 
    USING (EXISTS (
        SELECT 1 FROM public.range_sessions
        WHERE public.range_sessions.id = session_id 
        AND public.range_sessions.user_id = auth.uid()
    ));
CREATE POLICY "Users can insert shots to their own range sessions" 
    ON public.range_shots FOR INSERT 
    WITH CHECK (EXISTS (
        SELECT 1 FROM public.range_sessions
        WHERE public.range_sessions.id = session_id 
        AND public.range_sessions.user_id = auth.uid()
    ));
CREATE POLICY "Users can update shots in their own range sessions" 
    ON public.range_shots FOR UPDATE 
    USING (EXISTS (
        SELECT 1 FROM public.range_sessions
        WHERE public.range_sessions.id = session_id 
        AND public.range_sessions.user_id = auth.uid()
    ));
CREATE POLICY "Users can delete shots in their own range sessions" 
    ON public.range_shots FOR DELETE 
    USING (EXISTS (
        SELECT 1 FROM public.range_sessions
        WHERE public.range_sessions.id = session_id 
        AND public.range_sessions.user_id = auth.uid()
    ));

-- View for getting benchmark data per club
CREATE OR REPLACE VIEW public.club_benchmark_data AS
SELECT 
    rs.user_id,
    r.club,
    
    -- Distance metrics
    AVG(r.carry_distance_yards) AS avg_carry_yards,
    AVG(r.total_distance_yards) AS avg_total_yards,
    STDDEV(r.carry_distance_yards) AS consistency_yards,
    
    -- Launch metrics
    AVG(r.ball_speed_mph) AS avg_ball_speed_mph,
    AVG(r.height_feet) AS avg_height_feet,
    AVG(r.launch_angle_degrees) AS avg_launch_angle_degrees,
    AVG(r.launch_direction_degrees) AS avg_launch_direction_degrees,
    
    -- Accuracy metrics
    AVG(r.carry_side_feet) AS avg_carry_side_feet,
    AVG(r.from_pin_yards) AS avg_from_pin_yards,
    
    -- Efficiency metrics
    AVG(r.carry_efficiency) AS avg_carry_efficiency,
    AVG(r.height_to_carry_ratio) AS avg_height_to_carry_ratio,
    AVG(r.spin_to_launch_ratio) AS avg_spin_to_launch_ratio,
    
    -- Calculate consistency score (100 minus standard deviation percentage)
    (100 - (STDDEV(r.carry_distance_yards) / NULLIF(AVG(r.carry_distance_yards), 0) * 100)) AS consistency_score,
    
    -- Accuracy deviation (average distance from target)
    AVG(r.from_pin_yards) AS accuracy_deviation,
    
    -- Count of shots used for this benchmark
    COUNT(*) AS shots_count,
    
    -- Most recent shot timestamp
    MAX(r.created_at) AS last_shot_timestamp
FROM 
    public.range_shots r
JOIN 
    public.range_sessions rs ON r.session_id = rs.id
WHERE 
    r.club IS NOT NULL
GROUP BY 
    rs.user_id, r.club;